# Generated by Django 3.2.7 on 2021-10-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gulmohar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('availability', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
