# Generated by Django 3.2.8 on 2021-10-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_gulmohar_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gulmohar',
            name='image_src',
            field=models.ImageField(upload_to=''),
        ),
    ]
