# Generated by Django 3.2.7 on 2021-10-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_orders_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
